# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import picture_pb2 as picture__pb2


class GetPoseStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getPose = channel.unary_unary(
                '/picture.GetPose/getPose',
                request_serializer=picture__pb2.Picture.SerializeToString,
                response_deserializer=picture__pb2.Pose.FromString,
                )


class GetPoseServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetPoseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getPose': grpc.unary_unary_rpc_method_handler(
                    servicer.getPose,
                    request_deserializer=picture__pb2.Picture.FromString,
                    response_serializer=picture__pb2.Pose.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'picture.GetPose', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetPose(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/picture.GetPose/getPose',
            picture__pb2.Picture.SerializeToString,
            picture__pb2.Pose.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
